# Local overrides

services:
  ingress:
    environment:
      TRAEFIK_API_INSECURE: "true"
    ports:
      - "8080:80"
      - "8443:443"
      - "8081:8080"

  study-manager-backend:
    labels:
      'traefik.http.routers.studymanager-backend.rule': "Host(`studymanager.more.local.redlink.io`) && (PathPrefix(`/api`) || PathPrefix(`/login`) || PathPrefix(`/logout`))"
  study-manager-frontend:
    labels:
      'traefik.http.routers.studymanager-frontend.rule': "Host(`studymanager.more.local.redlink.io`)"
  data-gateway:
    labels:
      'traefik.http.routers.dsb-gateway.rule': "Host(`data.more.local.redlink.io`)"
  kibana:
    labels:
      'traefik.http.routers.kibana.rule': "Host(`kibana.more.local.redlink.io`)"
