# Local overrides

services:
  ingress:
    environment:
      TRAEFIK_API_INSECURE: "true"
    ports:
      - "8080:80"
      - "8443:443"
      - "8081:8080"

  study-manager-backend:
    labels:
      'traefik.http.routers.mmb-backend.rule': "Host(`studymanager.more.local.redlink.io`) && (PathPrefix(`/api`) || PathPrefix(`/login`) || PathPrefix(`/logout`))"
    environment:
      MMB_BASE_URL: 'http://studymanager.more.local.redlink.io:8080/api/v1'
      DSG_BASE_URL: 'http://dsb.more.local.redlink.io:8080/api/v1'
  study-manager-frontend:
    labels:
      'traefik.http.routers.mmb-frontend.rule': "Host(`studymanager.more.local.redlink.io`)"
  dsb-gateway:
    labels:
      'traefik.http.routers.dsb-gateway.rule': "Host(`dsb.more.local.redlink.io`)"
  kibana:
    labels:
      'traefik.http.routers.kibana.rule': "Host(`kibana.more.local.redlink.io`)"
