# Local overrides

services:
  ingress:
    environment:
      TRAEFIK_API_INSECURE: "true"
    ports:
      - "8080:80"
      - "8443:443"
      - "8081:8080"

  mmb-backend:
    labels:
      'traefik.http.routers.mmb-backend.rule': "Host(`mmb.more.local.redlink.io`) && PathPrefix(`/api`)"
  mmb-frontend:
    labels:
      'traefik.http.routers.mmb-frontend.rule': "Host(`mmb.more.local.redlink.io`)"
  dsb-gateway:
    labels:
      'traefik.http.routers.dsb-gateway.rule': "Host(`dsb.more.local.redlink.io`)"
  kibana:
    labels:
      'traefik.http.routers.kibana.rule': "Host(`kibana.more.local.redlink.io`)"
